"""
This module provides tools for handling files
It's no replacement for more standard modules ; I made it because I don't have
much knowledge about coding, and wanted functions that I use across several
scripts to handle files, especially the very specific format generated by
MAScriL, to be neatly packaged in a single place.
"""

from __future__ import print_function
import os
import tarfile
import json
import numpy as np

from typing import Text, Callable, List
from functools import wraps


def create_folder(path) :
    # type: (str) -> bool
    """
    Creates a folder, and all the parent folders in its arborescence.
    Does nothing if the target folder already exists.
    Works like os.makedirs, but without raising an error if the folder already
    exists.
    
    Parameters
    ----------
    path : string
        Path of the desired folder
    
    Returns
    -------
    callback : bool
        True if a new folder was created. False if it already existed.
    """
    try :
        os.makedirs(path)
        return True
    except FileExistsError :
        return False
create_folder.__annotations__ = {'path':Text, 'return':bool}




"""
The following function is a decorator function :
    a function intended to alter how other functions work.
Once you have defined a decorator like 'my_decorator', you can use
    the following syntax :

@my_decorator
def my_function(...) :
    ...

This acts a contraction of :

def my_function(...) :
    ...
my_function = my_decorator(my_function)
"""
def preserve_cwd(function) :
    # type: (Callable) -> Callable
    """
    Function decorator.
    Upon calling the decorated function, stores the initial value of the
    working directory ; sets the working directory to that value after the
    function call.
    """
    @wraps(function)
    def decorated_function(*args, **kwargs) :
        path = os.getcwd()
        returned_value = function(*args, **kwargs)
        os.chdir(path)
        return returned_value
    return decorated_function
preserve_cwd.__annotations__ = {'function':Callable, 'return':Callable}








## Treatment of the MAScriL-generated .txt files
"""
Of the following, the user intended function are select_observables, pack_txt
and unpack_txt ; the other functions of this section are merely intermediary
steps.
"""


def select_observables(lines, labels, renamed_labels={}) :
    # type: (List[Text], Collection[Text], Optional[Dict[Text, Text]]) -> List[Text]
    """
    Takes a list of strings, and a second list of strings.
    
    Interprets the first argument as the list of lines of a table, identifying
    tabulations as column separations.
    Trims the columns whose topmost element is not is not within the second
    list of strings, then returns the lines of the trimmed table.
    
    If the first line contains a comma, commas will be interpreted
    as column separators as well, but in either case the returned list will
    use tabulations as separators.
    
    Can take a dictionnary as a third, optional argument ; any string that
    appears in the key of the dictionnary and as the topmost element of a
    column will be replaced by the associated value stored in the dictionnary.
    """
    new_lines = select_columns(lines,
                               select_indices(lines, labels, renamed_labels))
    columns_titles = split_header(new_lines[0])
    for j, title in enumerate(columns_titles) :
        while title in renamed_labels.keys() :
            columns_titles[j] = renamed_labels[title]
            title = columns_titles[j]
    new_header = '#' + '\t'.join(columns_titles) + '\n'
    new_lines[0] = new_header
    return new_lines



def unpack_txt(lines) :
    header = {title:j for j,title in enumerate(split_header(lines[0]))}
    if ("," in lines[0]) and not ("\t" in lines[0]) :
        data = np.loadtxt(
          lines[1:],
          converters={k:interpret_bitstring for k,_ in enumerate(header)},
          delimiter = ","
          )
    else :
        data = np.loadtxt(
          lines[1:],
          converters={k:interpret_bitstring for k,_ in enumerate(header)}
          )
    return header, data



def split_header(header) :
    # type: (Text) -> List[Text]
    """
    Takes a string, and splits the part after its last '#' at each tabulation
    and comma. Intended use case is the first line of .txt datafiles saved from
    Qtiplot or MasCril, to get all the column titles.
    """
    return header.strip().split("#")[-1].replace(",","\t").split("\t")

def select_columns(lines, selected_indices) :
    # type: (List[Text], Collection[Text]) -> List[Text]
    """
    Takes a list of strings, and a list of integers.
    
    Interprets the first argument as the list of lines of a table, identifying
    tabulations as column separations.
    Trims the columns whose indices are not in the list of integers, then 
    returns the lines of the trimmed table.
    
    If the first line contains a comma, commas will be interpreted
    as column separators as well, but in either case the returned list will
    use tabulations as separators.
    """
    columns_titles = split_header(lines[0])
    amount_of_columns = len(columns_titles)
    good_indices = [i for i in selected_indices if i < amount_of_columns]
    selected_columns_titles = [columns_titles[i] for i in good_indices]
    new_lines = ['#' + '\t'.join(selected_columns_titles) + '\n']
    comma_separated_values = ("," in lines[0])
    for line in lines[1:] :
        if comma_separated_values :
            line = line.replace(",", "\t")
        values = line.strip().split('\t')
        selected_values = [values[i] for i in good_indices]
        new_lines.append('\t'.join(selected_values) + '\n')
    return new_lines

def select_indices(lines, labels, renamed_labels={}) :
    # type: (List[Text], Collection[Text], Optional[Dict[Text, Text]]) -> List[Text]
    """
    Takes a list of strings, and a second list of strings.
    
    Interprets the first argument as the list of lines of a table, identifying
    tabulations as column separations.
    Returns the indices of the columns whose topmost element is within the 
    second list of strings.
    
    If the first line contains a comma, commas will be interpreted
    as column separators as well.
    
    Can take a dictionnary as a third, optional argument ; any string that
    appears in the key of the dictionnary will be interpreted as the associated
    value stored in the dictionnary.
    """
    columns_titles = split_header(lines[0])
    for j, title in enumerate(columns_titles) :
        while title in renamed_labels.keys() :
            columns_titles[j] = renamed_labels[title]
            title = columns_titles[j]
    selected_columns = []
    for label in labels :
        try :
            selected_columns.append(columns_titles.index(label))
        except ValueError :
            print(f"⚠ No {label} in the data ⚠")
            # to replace by a raised warning ?
    return selected_columns






# Treatment of .txt files in general

@preserve_cwd
def save_as_txt(lines, filename, path) :
    output_filepath = os.path.join(path, filename)
    if os.path.exists(output_filepath) :
        print(f"‼️ Overwriting {output_filepath}")
    else :
        print(f"✍🏽 Writing {output_filepath}")
    with open(output_filepath, 'w') as output_file :
        output_file.writelines(lines)


def interpret_bitstring(bitstring) :
    return interpret_string(bitstring.decode())  


def interpret_string(string) :
    string = string.strip()
    if string in ["None", ""] :
        return None
    string = ".".join(string.split(","))
    return float(string)
